name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Déployer sur EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}        
          username: ${{ secrets.EC2_USER }}      
          key: ${{ secrets.EC2_SSH_KEY }}  
        
          script: |
            # 1. Aller dans le dossier
            mkdir -p /home/${{ secrets.EC2_USER }}/projet_test1
            cd /home/${{ secrets.EC2_USER }}/projet_test1
            
            # 2. Gestion du Git (Note le "." à la fin du clone)
            if [ ! -d ".git" ]; then
              echo "Premier déploiement..."
              git clone https://github.com/Yapi41/mon-projetDocker.git .
            else
              echo "Mise à jour..."
              git pull origin main
            fi
            
            # 3. Fichier .env
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            
            # 4. Relancer les conteneurs
            # On teste 'docker compose' (version moderne)
            sudo docker compose down
            sudo docker compose up -d --build