name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Déployer sur EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}        
          username: ${{ secrets.EC2_USER }}      
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: |
            # 1. Aller dans le dossier du projet
            cd /home/test_user/projet_test1
            
            # 2. Si le dossier est vide, on clone. Sinon, on pull.
            if [ ! -d ".git" ]; then
              echo "Premier déploiement : Clonage du dépôt..."
              git clone https://github.com/Yapi41/mon-projetDocker.git
            else
              echo "Mise à jour du code..."
              git pull origin main
            fi

            
            # 3. Recréer le fichier .env sur le serveur AWS
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            
            # 4. Relancer les conteneurs 
            sudo docker-compose down
            sudo docker-compose up -d --build